### ISSUE TITLE
OpenId Logout button using Keycloak

### ISSUE THREAD

**Issue by imrushi** [lgdd/openid-connect-single-button#1]
Hi @lgdd , Thank you for making such a great example repository.
I'd like to add a Logout/Sign Out button that will log the user out of SSO and prompt them for Keycloak authentication again when they log in.

Currently when the user logs in after that when he clicks on Liferay Sign Out. It is not signed out from SSO and again logged in without Authentication.

**Comment by lgdd** [comment]
Hi @imrushi ! Thanks for your kind words :)

Indeed, in this example, when logging out we close the Liferay session but not the Keycloak session. I believe that in order to do that, we would need a `PostLogoutAction` component calling Keycloak to close the session. A bit similar to what my colleague did [here](https://github.com/fabian-bouche-liferay/oidc-userinfo-mapping/blob/master/modules/userinfo-mapping/src/main/java/com/liferay/samples/fbo/oidc/userinfo/mapping/action/OIDCRoleMappingPostLoginAction.java) with a `PostLoginAction` to get the `user-info` from OIDC and map the attributes to the Liferay user.

I'll add the component with a configuration to choose to close or not both sessions.

Thanks for your feedback!

**Comment by Shikatao** [comment]
Hello, tell me, please, did you find a solution?

**Comment by lgdd** [comment]
See the ticket on Liferay Issues: https://liferay.atlassian.net/browse/LPD-412

**Comment by lgdd** [comment]
You should find the code you're looking for here: https://github.com/fabian-bouche-liferay/saml-user-group-mapping/blob/master/modules/oidc-logout/src/main/java/com/liferay/samples/fbo/oidc/logout/BackchannelLogoutServlet.java
